services:
  postgres:
    image: postgres:17
    container_name: melur-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: nammamelur
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: MelurApp$2026
    ports:
      - "5432:5432"
    volumes:
      - melur_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U melur -d melur"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  melur_postgres_data: